### ISSUE TITLE
Where do I download the latest WIndows release? 

### ISSUE THREAD

**Issue by Spidgeon1** [jrassa/EmulationStation#163]
It use to be available here. Why is the offical website still not updated?

**Comment by jrassa** [comment]
There was a dependency issue with the continuous build.  It has been resolved.

The official website has not been updated because there have been no new official releases.  It is my understanding that the original developer of EmulationStation has abandon the project.

The releases provided here are unofficial windows builds of the RetroPie version of EmulationStation.
